[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PAAS"
description = "The real deal"
version = "0.0.1"
dependencies = [
  "numpy",
  "pytest",
  "pyserial",
  "opencv-python"
]
requires-python = ">= 3.9"
authors = []

[tool.setuptools]
packages = ["inverse_kinematics", "core", "py2motor"]
